name = "discord-proleto"
main = "src/index.ts"
compatibility_date = "2023-05-29"
workers_dev = false
route = "voc.pet/proleto/*"
kv_namespaces = [
    { binding = "DATA", id = "5630505baf5b44c79b0853d0b15e6e86" }
]

[vars]
WORSHIP_CHANNEL_ID = "702953546106273855"

[triggers]
crons = [
    "*/10 * * * *"
]